### ISSUE TITLE
Remove support for | and : separators

### ISSUE THREAD

**Issue by yisibl** [yisibl/postcss-aspect-ratio-mini#9]
Now that browsers natively support the aspect-ratio property, we try to align ourselves with the specification.

https://drafts.csswg.org/css-sizing-4/#aspect-ratio

```css
.aspect-box {
    aspect-ratio: 16 : 9;
}

.aspect-box {
    aspect-ratio: 16 | 9;
}
```
